# Generated by Django 2.1.2 on 2018-10-31 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('institue_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('institute_type', models.CharField(max_length=100)),
                ('institute_profile_pic_path', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=50)),
                ('director_pic_path', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('upload_date', models.CharField(max_length=50)),
                ('expir_date', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Intersts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('upload_date', models.CharField(max_length=50)),
                ('expir_date', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('upload_date', models.CharField(max_length=50)),
                ('expir_date', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Societies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society', models.CharField(max_length=50)),
                ('profile_pic_path', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('instite_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicapp.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='User_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('profile_pic_path', models.CharField(max_length=50)),
                ('desc_internship', models.CharField(max_length=1000)),
                ('desc_scholarship', models.CharField(max_length=50)),
                ('desc_project', models.CharField(max_length=50)),
                ('skill_set', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='scholarship',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicapp.User_Table'),
        ),
        migrations.AddField(
            model_name='project',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicapp.User_Table'),
        ),
        migrations.AddField(
            model_name='intersts',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicapp.User_Table'),
        ),
        migrations.AddField(
            model_name='internship',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicapp.User_Table'),
        ),
    ]
