# Generated by Django 2.1.2 on 2018-11-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_auto_20181102_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
