# Generated by Django 2.1.2 on 2018-11-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0004_auto_20181102_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
