# Generated by Django 2.1.2 on 2018-11-03 17:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0006_auto_20181103_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicapp.Newsfeed')),
            ],
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
