# Generated by Django 2.1.2 on 2018-11-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0008_auto_20181103_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfeed',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='user_table',
            name='desc_internship',
        ),
        migrations.RemoveField(
            model_name='user_table',
            name='desc_project',
        ),
        migrations.RemoveField(
            model_name='user_table',
            name='desc_scholarship',
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='news_feed_type',
            field=models.CharField(choices=[('intership', 'Internship'), ('scholarship', 'Scholarship'), ('programmes', 'Programmes'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
