# Generated by Django 2.1.2 on 2018-12-20 13:23

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('basicapp', '0012_auto_20181220_1321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interests',
            new_name='Interest',
        ),
    ]
